version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: shoppinglist-mysql
    environment:
      MYSQL_DATABASE: shoppinglist
      MYSQL_USER: shoppinglist
      MYSQL_PASSWORD: shoppinglist
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
