package com.scottvarns.shoppinglist.security;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.security.core.context.SecurityContextHolder;

import static org.assertj.core.api.Assertions.assertThat;

@TestMethodOrder(MethodOrderer.MethodName.class)
class JwtAuthenticationFilterTest {

    private static final String TEST_SECRET =
            "c2hvcHBpbmdsaXN0LXRlc3Qtc2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTMyLWJ5dGVz";

    @AfterEach
    void clearSecurityContext() {
        SecurityContextHolder.clearContext();
    }

    /**
     * When a request contains a valid bearer token
     * Then the filter authenticates the request with the token's user ID as its principal.
     */
    @Test
    void test01_doFilterInternal_whenValidBearerTokenProvided_thenSetsAuthenticatedUserId() throws Exception {
        // Create a JwtService with a test secret and a token expiration time of 3600 seconds (1 hour)
        JwtService jwtService = new JwtService(TEST_SECRET, 3600);

        // Create a JwtAuthenticationFilter with the created JwtService
        JwtAuthenticationFilter filter = new JwtAuthenticationFilter(jwtService);

        // Create a mock HTTP request and add an Authorization header with a valid bearer token generated by the JwtService for user ID 42 and email user@example.com
        MockHttpServletRequest request = new MockHttpServletRequest();
        request.addHeader("Authorization", "Bearer " + jwtService.generateToken(42L, "user@example.com"));

        // Call the filter's doFilter method with the mock request, a mock response, and a lambda that asserts that the SecurityContextHolder's authentication principal is equal to 42L
        filter.doFilter(request, new MockHttpServletResponse(), (servletRequest, servletResponse) ->
                assertThat(SecurityContextHolder.getContext().getAuthentication().getPrincipal()).isEqualTo(42L)
        );
    }

    /**
     * When a request contains an invalid bearer token
     * Then the filter does not authenticate the request and clears the security context.
     */
    @Test
    void test02_doFilterInternal_whenInvalidBearerTokenProvided_thenClearsSecurityContext() throws Exception {
        // Create a JwtService with a test secret and a token expiration time of 3600 seconds (1 hour)
        JwtService jwtService = new JwtService(TEST_SECRET, 3600);

        // Create a JwtAuthenticationFilter with the created JwtService
        JwtAuthenticationFilter filter = new JwtAuthenticationFilter(jwtService);

        // Create a mock HTTP request and add an Authorization header with an invalid bearer token
        MockHttpServletRequest request = new MockHttpServletRequest();
        request.addHeader("Authorization", "Bearer invalid.token.here");

        // Call the filter's doFilter method with the mock request, a mock response, and a lambda that asserts that the SecurityContextHolder's authentication is null
        filter.doFilter(request, new MockHttpServletResponse(), (servletRequest, servletResponse) ->
                assertThat(SecurityContextHolder.getContext().getAuthentication()).isNull()
        );
    }

    /**
     * When a request contains an incorrect autnhorization header (not starting with "Bearer ")
     * Then the filter does not authenticate the request and clears the security context.
     */
    @Test
    void test03_doFilterInternal_whenInvalidAuthTypeProvided_thenClearsSecurityContext() throws Exception {
        // Create a JwtService with a test secret and a token expiration time of 3600 seconds (1 hour)
        JwtService jwtService = new JwtService(TEST_SECRET, 3600);

        // Create a JwtAuthenticationFilter with the created JwtService
        JwtAuthenticationFilter filter = new JwtAuthenticationFilter(jwtService);

        // Create a mock HTTP request and add an Authorization header with an incorrect auth type (not starting with "Bearer ")
        MockHttpServletRequest request = new MockHttpServletRequest();
        request.addHeader("Authorization", "Basic 123");

        // Call the filter's doFilter method with the mock request, a mock response, and a lambda that asserts that the SecurityContextHolder's authentication is null
        filter.doFilter(request, new MockHttpServletResponse(), (servletRequest, servletResponse) ->
                assertThat(SecurityContextHolder.getContext().getAuthentication()).isNull()
        );
    }
}
